# Generated by Django 3.0.5 on 2020-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='original_title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
