# Generated by Django 3.0.5 on 2020-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_charts', '0003_auto_20200423_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='air_date',
            field=models.DateField(null=True),
        ),
    ]
