# Generated by Django 3.0.5 on 2020-04-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_charts', '0004_auto_20200423_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ['-votes']},
        ),
    ]
